version: '3'

services:
  db:
    user: ${uid}:${gid}
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - $PGPORT:$PGPORT

  # payload:
  #   image: node:18-alpine
  #   user: '${uid}:${gid}'
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./payload-cms:/home/node/app
  #   working_dir: /home/node/app/
  #   command: sh -c "yarn install && yarn dev"
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URI: postgres://$PGUSER:$PGPASSWORD@db:$PGPORT/$PGDATABASE
  #     PORT: 3000
  #     NODE_ENV: development
  #     PAYLOAD_SECRET: TESTING

  # frontend:
  #   image: node:18-alpine
  #   user: '${uid}:${gid}'
  #   working_dir: '/home/node/bias180'
  #   volumes:
  #     - ./frontend:/home/node/bias180
  #   command: sh -c "npm install && npm run dev"
  #   environment:
  #     - BACKEND_SERVER=payload:3000
  #   restart: unless-stopped
  #   ports:
  #     - 9000:9000
  #   depends_on:
  #     - payload
